apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers # Required. Kafka broker connection setting
      value: "localhost:9092,dapr-kafka.myapp.svc.cluster.local:9093"
    - name: consumerGroup # Optional. Used for input bindings.
      value: "GroupA"
    - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
      value: "serviceA"
    - name: authType # Required.
      value: "none"
    - name: authRequired
      value: "false"
    - name: consumeRetryInterval # Optional.
      value: "200ms"
    #    - name: version # Optional.
    #      value: 0.10.2.0
    - name: disableTls # Optional. Disable TLS. This is not safe for production!! You should read the `Mutual TLS` section for how to use TLS.
      value: "true"
  scopes:
    - serviceA
    - serviceB
